-- MySQL Script generated by MySQL Workbench
-- Tue Feb  8 22:14:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectmanagement_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectmanagement_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectmanagement_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projectmanagement_db` ;

-- -----------------------------------------------------
-- Table `projectmanagement_db`.`User_Authority_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectmanagement_db`.`User_Authority_Table` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `User_Authority` VARCHAR(10) NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmanagement_db`.`User_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectmanagement_db`.`User_Table` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Account` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmanagement_db`.`Issue_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectmanagement_db`.`Issue_Table` (
  `Issue_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NULL,
  `Date` DATE NULL,
  `Title` VARCHAR(45) NULL,
  `Content` MEDIUMTEXT NULL,
  PRIMARY KEY (`Issue_ID`),
  INDEX `User_ID_idx` (`User_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmanagement_db`.`Issue_Priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectmanagement_db`.`Issue_Priority` (
  `Issue_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NULL,
  `Priority` VARCHAR(45) NULL,
  PRIMARY KEY (`Issue_ID`),
  INDEX `User ID_idx` (`User_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmanagement_db`.`Issue_Severity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectmanagement_db`.`Issue_Severity` (
  `Issue_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NULL,
  `Severity` VARCHAR(45) NULL,
  PRIMARY KEY (`Issue_ID`),
  INDEX `User_ID_idx` (`User_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectmanagement_db`.`Issue_Assign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectmanagement_db`.`Issue_Assign` (
  `Issue_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Issue_ID`),
  INDEX `User_ID_idx` (`User_ID` ASC) VISIBLE)
ENGINE = InnoDB;

USE `projectmanagement_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `projectmanagement_db`.`Issue_Table_vt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectmanagement_db`.`Issue_Table_vt` (`No` INT, `Name` INT, `Date` INT, `Title` INT, `Priority` INT, `Severity` INT);

-- -----------------------------------------------------
-- Placeholder table for view `projectmanagement_db`.`User_Table_vt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectmanagement_db`.`User_Table_vt` (`Account` INT, `Password` INT, `Name` INT, `Authority` INT);

-- -----------------------------------------------------
-- View `projectmanagement_db`.`Issue_Table_vt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmanagement_db`.`Issue_Table_vt`;
USE `projectmanagement_db`;
CREATE  OR REPLACE VIEW `Issue_Table_vt`(No,Name,Date,Title,Priority,Severity) 
AS select Issue_Table.Issue_ID,Issue_Assign.Name,Issue_Table.Date,Issue_Table.Title,Issue_Priority.Priority,Issue_Severity.Severity 
from Issue_Table,Issue_Priority,Issue_Assign, Issue_Severity 
where Issue_Table.Issue_ID = Issue_Assign.Issue_ID and Issue_Table.Issue_ID = Issue_Priority.Issue_ID and Issue_Table.Issue_ID = Issue_Severity.Issue_ID;

-- -----------------------------------------------------
-- View `projectmanagement_db`.`User_Table_vt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectmanagement_db`.`User_Table_vt`;
USE `projectmanagement_db`;
CREATE  OR REPLACE VIEW `User_Table_vt`(Account,Password,Name,Authority) 
AS select User_Table.Account, User_Table.Password, User_Table.Name, User_Authority_Table.User_Authority
from User_Table,User_Authority_Table
Where User_Table.User_ID = User_Authority_Table.User_ID;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
